export const RESET_STATE = "RESET_STATE";

export const FETCH_RECENT_WINNERS_SUCCESS = "FETCH_RECENT_WINNERS_SUCCESS";
export const FETCH_RECENT_WINNERS_FAILURE = "FETCH_RECENT_WINNERS_FAILURE";

export const CHANGE_ISRECENTWINNERS = "CHANGE_ISRECENTWINNERS";
