export const CHANGE_PLAYER_ADDRESS = "STORE_PLAYER_ADDRESS";
export const FETCH_PLAYER_DATA = "FETCH_PLAYER_DATA";
export const FETCH_PLAYER_DATA_SUCCESS = "FETCH_PLAYER_DATA_SUCCESS";
export const FETCH_PLAYER_DATA_FAILURE = "FETCH_PLAYER_DATA_FAILURE";

export const CHANGE_ISPLAYERLOADED = "CHANGE_ISPLAYERLOADED";

export const CHANGE_PLAYER_ISWAITING = "CHANGE_PLAYER_ISWAITING";

export const CHANGE_PLAYER_LATESTGUESS = "CHANGE_PLAYER_LATESTGUESS";
export const CHANGE_PLAYER_OUTCOME = "CHANGE_PLAYER_OUTCOME";
